### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by yudistirasd** [EcomPHP/shopee-php#1]
I am currently working on a project to connect the warehouse system to shopee, is there any documentation to use this package?
does it support multiple shopee accounts?
can be used in laravel?
can I contribute?

**Comment by nVuln** [comment]
this project still not finished, document not available yet
you're welcome to contribute, just open a PR

I'll give you some example for starting

```php
use EcomPHP\Shopee\Client;

$client = new Client('partner id', 'partner key');
```

to generate authorization url

```php
$auth = $client->auth();
$url = $auth->createAuthRequest('callback url');
redirect_to($url);
```

get token by authorization code

```php
$token = $auth->getToken($request->code, $request->shop_id);
```

set access token before call api
```php
$client->setAccessToken('access token');
```

call api to get order list
```php
$client->Order->getOrderList(['response_optional_fields' => 'order_status']);
```

for other api you can view source code in [Resources](https://github.com/EcomPHP/shopee-php/tree/master/src/Resources) folder
